// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	token.proto

It has these top-level messages:
	UserId
	UserToken
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type UserId struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *UserId) Reset()                    { *m = UserId{} }
func (m *UserId) String() string            { return proto1.CompactTextString(m) }
func (*UserId) ProtoMessage()               {}
func (*UserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type UserToken struct {
	UserId int64  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *UserToken) Reset()                    { *m = UserToken{} }
func (m *UserToken) String() string            { return proto1.CompactTextString(m) }
func (*UserToken) ProtoMessage()               {}
func (*UserToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserToken) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto1.RegisterType((*UserId)(nil), "proto.UserId")
	proto1.RegisterType((*UserToken)(nil), "proto.UserToken")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TokenService service

type TokenServiceClient interface {
	Get(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserToken, error)
	Create(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserId, error)
	Update(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserId, error)
	Delete(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error)
}

type tokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewTokenServiceClient(cc *grpc.ClientConn) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) Get(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserToken, error) {
	out := new(UserToken)
	err := grpc.Invoke(ctx, "/proto.TokenService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) Create(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := grpc.Invoke(ctx, "/proto.TokenService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) Update(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := grpc.Invoke(ctx, "/proto.TokenService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) Delete(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := grpc.Invoke(ctx, "/proto.TokenService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenService service

type TokenServiceServer interface {
	Get(context.Context, *UserId) (*UserToken, error)
	Create(context.Context, *UserToken) (*UserId, error)
	Update(context.Context, *UserToken) (*UserId, error)
	Delete(context.Context, *UserId) (*UserId, error)
}

func RegisterTokenServiceServer(s *grpc.Server, srv TokenServiceServer) {
	s.RegisterService(&_TokenService_serviceDesc, srv)
}

func _TokenService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).Get(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).Create(ctx, req.(*UserToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).Update(ctx, req.(*UserToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).Delete(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TokenService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TokenService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TokenService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TokenService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token.proto",
}

func init() { proto1.RegisterFile("token.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x72, 0x5c, 0x6c, 0xa1,
	0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x8e, 0x92, 0x25, 0x17, 0x27, 0x48, 0x3e, 0x04, 0xa4, 0x53,
	0x48, 0x8c, 0x8b, 0xad, 0x14, 0xac, 0x18, 0xaa, 0x06, 0xca, 0x03, 0x69, 0x05, 0x1b, 0x2d, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x18, 0xed, 0x61, 0xe4, 0xe2, 0x01, 0xeb, 0x0b, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe0, 0x62, 0x76, 0x4f, 0x2d, 0x11, 0xe2, 0x85, 0xb8,
	0x40, 0x0f, 0x62, 0xaf, 0x94, 0x00, 0x12, 0x17, 0xac, 0x5c, 0x89, 0x41, 0x48, 0x9b, 0x8b, 0xcd,
	0xb9, 0x28, 0x35, 0xb1, 0x24, 0x55, 0x08, 0x43, 0x56, 0x0a, 0x55, 0x3b, 0x44, 0x71, 0x68, 0x41,
	0x0a, 0x91, 0x8a, 0x35, 0xb8, 0xd8, 0x5c, 0x52, 0x73, 0x52, 0x4b, 0x52, 0xd1, 0x9d, 0x81, 0xae,
	0x32, 0x89, 0x0d, 0xcc, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x69, 0xd1, 0x62, 0x64, 0x36,
	0x01, 0x00, 0x00,
}
